server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:16432/server_registry
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.xml

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
